spring.datasource.url=mysql://root:AnquaIQKxefbUUlkeGatkDnYCMvtdbVi@mysql.railway.internal:3306/railway
spring.datasource.username=root
spring.datasource.password=AnquaIQKxefbUUlkeGatkDnYCMvtdbVi

#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
