spring.application.name=bakery

# 1. DATABASE (Smart Logic)
# If we are on Railway, use the Env Variables. 
# If we are on Laptop, default to localhost.
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/bakery}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:12345678}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. JPA / HIBERNATE
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 3. SERVER PORT (The Most Important Line)
# Tells the app: "Use the PORT variable if Railway gives one. If not, use 8080."
server.port=${PORT:8080}
server.address=0.0.0.0